import sqlite3
con = sqlite3.connect("game.db")
cur = con.cursor()

cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='sentences';")
table_exists = cur.fetchone()

if not table_exists:
    cur.execute("""CREATE TABLE IF NOT EXISTS sentences (
    difficulty VARCHAR(50) NOT NULL,
    language VARCHAR(50) NOT NULL,
    sentence TEXT NOT NULL)""")

    cur.execute("""INSERT INTO sentences (difficulty, language, sentence) VALUES
    ('easy', 'english', 'I need to buy some bread.'),
    ('easy', 'english', 'The weather is sunny today.'),
    ('easy', 'english', 'She loves reading books in the evening.'),
    ('easy', 'english', 'Can you help me with my homework?'),
    ('easy', 'english', 'I went to the market to buy vegetables.'),
    ('easy', 'english', 'He is playing soccer with his friends.'),
    ('easy', 'english', 'The cat is sleeping on the sofa.'),
    ('easy', 'english', 'I like to drink coffee in the morning.'),
    ('easy', 'english', 'They are watching a movie right now.'),
    ('easy', 'english', 'The dog barked loudly in the yard.'),
    ('easy', 'english', 'She is reading a book on the couch.'),
    ('easy', 'english', 'I have a new phone.'),
    ('easy', 'english', 'My friend is coming over tomorrow.'),
    ('easy', 'english', 'I like to eat pizza on weekends.'),
    ('easy', 'english', 'The children are playing outside.'),
    ('easy', 'english', 'I need to buy some milk.'),
    ('easy', 'english', 'We are going to the park later.'),
    ('easy', 'english', 'She likes to listen to music in the car.'),
    ('easy', 'english', 'The teacher is explaining the lesson.'),
    ('easy', 'english', 'I’m feeling very tired today.'),
    ('easy', 'english', 'He is my best friend.'),
    ('easy', 'english', 'She is wearing a red dress.'),
    ('easy', 'english', 'I love watching movies on Friday nights.'),
    ('easy', 'english', 'I like to read books before bed.'),
    ('easy', 'english', 'We had lunch at the new restaurant.'),
    ('easy', 'english', 'My brother is very tall.'),
    ('easy', 'english', 'The baby is crying in the crib.'),
    ('easy', 'english', 'I enjoy walking in the park.'),
    ('easy', 'english', 'I’m going to the store to buy groceries.'),
    ('easy', 'english', 'He is making breakfast right now.'),
    ('easy', 'english', 'She is going to the gym this evening.'),
    ('easy', 'english', 'I’m going to visit my grandmother tomorrow.'),
    ('easy', 'english', 'We are having a barbecue this weekend.'),
    ('easy', 'english', 'I need to find my keys.'),
    ('easy', 'english', 'She is taking a nap right now.'),
    ('easy', 'english', 'I love traveling to new places.'),
    ('easy', 'english', 'My parents are out of town this week.'),
    ('easy', 'english', 'He is always happy to help others.'),
    ('easy', 'english', 'We are going on vacation next month.'),
    ('easy', 'english', 'My favorite color is blue.'),
    ('easy', 'english', 'I like to eat ice cream in the summer.'),
    ('easy', 'english', 'I went for a run this morning.'),
    ('easy', 'english', 'They are playing video games together.'),
    ('easy', 'english', 'I need to clean my room.'),
    ('easy', 'english', 'The baby is learning to walk.'),
    ('easy', 'english', 'I saw a bird flying in the sky.'),
    ('easy', 'english', 'I’m studying for my exams.'),
    ('easy', 'english', 'He is very good at math.'),
    ('easy', 'english', 'We are going to a concert this evening.');""")

    cur.execute("""INSERT INTO sentences (difficulty, language, sentence) VALUES
    ('intermediate', 'english', 'She is planning to move to another city next year.'),
    ('intermediate', 'english', 'I’ve been working on this project for a month now.'),
    ('intermediate', 'english', 'He took the book from the shelf and started reading it.'),
    ('intermediate', 'english', 'We need to finish this task by the end of the day.'),
    ('intermediate', 'english', 'She always carries an umbrella when it looks like rain.'),
    ('intermediate', 'english', 'I couldn’t find my keys this morning, so I was late.'),
    ('intermediate', 'english', 'They are preparing for the conference next week.'),
    ('intermediate', 'english', 'The team is practicing for the big match tomorrow.'),
    ('intermediate', 'english', 'She bought a new dress for the party this weekend.'),
    ('intermediate', 'english', 'He enjoys cooking meals for his family on Sundays.'),
    ('intermediate', 'english', 'I’ve heard that the new restaurant is really good.'),
    ('intermediate', 'english', 'The students are working on their final projects.'),
    ('intermediate', 'english', 'They went to the beach to enjoy the sunset last night.'),
    ('intermediate', 'english', 'I just finished reading a book about history.'),
    ('intermediate', 'english', 'We are going to explore the city tomorrow.'),
    ('intermediate', 'english', 'She asked for directions to the nearest library.'),
    ('intermediate', 'english', 'I’m planning to start a new hobby next month.'),
    ('intermediate', 'english', 'They were discussing their plans for the weekend.'),
    ('intermediate', 'english', 'He is studying French because he plans to travel to Paris.'),
    ('intermediate', 'english', 'I’ve been feeling a bit under the weather lately.'),
    ('intermediate', 'english', 'The children were excited to go on the school trip.'),
    ('intermediate', 'english', 'I’m going to try a new recipe for dinner tonight.'),
    ('intermediate', 'english', 'She was reading a novel about adventure and mystery.'),
    ('intermediate', 'english', 'We need to clean the house before the guests arrive.'),
    ('intermediate', 'english', 'The teacher gave us an interesting assignment for the week.'),
    ('intermediate', 'english', 'I spent the afternoon at the library preparing for my exams.'),
    ('intermediate', 'english', 'He spent the evening at a meeting with his colleagues.'),
    ('intermediate', 'english', 'I need to buy a new laptop because mine is getting old.'),
    ('intermediate', 'english', 'They decided to take a vacation in the mountains this summer.'),
    ('intermediate', 'english', 'She is learning how to play the guitar in her free time.'),
    ('intermediate', 'english', 'We are going to the museum to see the new exhibition.'),
    ('intermediate', 'english', 'I’ve been working on improving my fitness level.'),
    ('intermediate', 'english', 'He decided to change his career and move to another industry.'),
    ('intermediate', 'english', 'I love spending time with my friends on the weekends.'),
    ('intermediate', 'english', 'The concert was amazing, and we had so much fun.'),
    ('intermediate', 'english', 'She is very creative and loves painting in her spare time.'),
    ('intermediate', 'english', 'I am looking forward to the holidays this year.'),
    ('intermediate', 'english', 'They stayed up late watching a new movie on Netflix.'),
    ('intermediate', 'english', 'He usually goes jogging in the morning before work.'),
    ('intermediate', 'english', 'We are hosting a dinner party at our house this weekend.'),
    ('intermediate', 'english', 'The project is due in two weeks, so we need to work hard.'),
    ('intermediate', 'english', 'She is planning to study abroad for her postgraduate degree.'),
    ('intermediate', 'english', 'I’m excited about the new book I just started reading.'),
    ('intermediate', 'english', 'We spent the afternoon walking around the city center.'),
    ('intermediate', 'english', 'The company is launching a new product next month.'),
    ('intermediate', 'english', 'They discussed their plans for the upcoming holiday season.'),
    ('intermediate', 'english', 'She is participating in a cooking competition this weekend.'),
    ('intermediate', 'english', 'I need to buy some new clothes for the winter season.');""")

    cur.execute("""INSERT INTO sentences (difficulty, language, sentence) VALUES
    ('hard', 'english', 'Despite the heavy rain, they decided to continue their journey without hesitation.'),
    ('hard', 'english', 'The politician delivered a powerful speech about the future of the economy and education.'),
    ('hard', 'english', 'He was caught in a moral dilemma, unsure of what decision would be the right one.'),
    ('hard', 'english', 'The scientist presented an innovative theory that challenged existing beliefs in the field.'),
    ('hard', 'english', 'She was reluctant to accept the offer, as she had doubts about the company’s reputation.'),
    ('hard', 'english', 'After a thorough analysis, the experts concluded that the data was inconclusive and flawed.'),
    ('hard', 'english', 'The novel explored complex themes of identity, loss, and redemption in the modern world.'),
    ('hard', 'english', 'They embarked on a quest to uncover the truth behind the mysterious disappearance.'),
    ('hard', 'english', 'His relentless pursuit of perfection often led to frustration and burnout.'),
    ('hard', 'english', 'The philosopher’s ideas revolutionized the way people perceive reality and existence.'),
    ('hard', 'english', 'Despite the challenges, the team remained resilient and determined to achieve their goals.'),
    ('hard', 'english', 'The artist’s work was a fusion of traditional techniques and contemporary concepts.'),
    ('hard', 'english', 'They conducted a series of experiments to validate their hypothesis, but the results were inconclusive.'),
    ('hard', 'english', 'The economic downturn had a significant impact on the job market and consumer confidence.'),
    ('hard', 'english', 'She wrote an elaborate essay discussing the philosophical implications of artificial intelligence.'),
    ('hard', 'english', 'The government’s policies have been criticized for their lack of foresight and long-term planning.'),
    ('hard', 'english', 'The meeting was highly productive, with members presenting detailed reports and actionable solutions.'),
    ('hard', 'english', 'The architect’s vision for the new city center was bold and ambitious, focusing on sustainability.'),
    ('hard', 'english', 'She was deeply moved by the documentary, which highlighted the plight of refugees around the world.'),
    ('hard', 'english', 'His innovative approach to problem-solving has made him a leading figure in the tech industry.'),
    ('hard', 'english', 'The historical significance of the site cannot be overstated, as it represents a key moment in history.'),
    ('hard', 'english', 'The novel’s narrative structure was non-linear, jumping between different timelines and perspectives.'),
    ('hard', 'english', 'They were confronted with a moral conundrum that tested their values and principles.'),
    ('hard', 'english', 'The psychological effects of isolation on individuals have been studied extensively by researchers.'),
    ('hard', 'english', 'He struggled to reconcile his ambition with his desire for a balanced and fulfilling life.'),
    ('hard', 'english', 'The artist’s work sparked a debate about the role of art in society and its potential for social change.'),
    ('hard', 'english', 'The company’s decision to expand into international markets was met with both excitement and skepticism.'),
    ('hard', 'english', 'She spoke passionately about the need for urgent reforms in the healthcare system.'),
    ('hard', 'english', 'Despite the overwhelming evidence, the defendant maintained his innocence throughout the trial.'),
    ('hard', 'english', 'The study revealed that there is a strong correlation between mental health and physical activity.'),
    ('hard', 'english', 'He wrote a detailed analysis of the economic policies that have shaped the country’s growth over the years.'),
    ('hard', 'english', 'The philosopher’s critique of modern society raised important questions about ethics and morality.'),
    ('hard', 'english', 'Their journey to the remote island was fraught with obstacles, but they persevered through adversity.'),
    ('hard', 'english', 'The research team discovered a groundbreaking method to reduce carbon emissions in industrial processes.'),
    ('hard', 'english', 'She was deeply affected by the loss of a loved one, and it took her years to heal emotionally.'),
    ('hard', 'english', 'The discovery of the ancient manuscript shed new light on the history of the civilization.'),
    ('hard', 'english', 'He spent years developing a theory that challenged the prevailing scientific consensus in his field.'),
    ('hard', 'english', 'The speech focused on the importance of collaboration between governments, businesses, and communities.'),
    ('hard', 'english', 'The ethical implications of genetic engineering remain a topic of intense debate among scientists.'),
    ('hard', 'english', 'The novel’s portrayal of human nature was both insightful and thought-provoking.'),
    ('hard', 'english', 'They argued that the political system needed reform in order to address the growing issues of inequality.'),
    ('hard', 'english', 'His research on quantum mechanics has revolutionized the way we understand the universe.'),
    ('hard', 'english', 'The environmental consequences of industrialization have had a profound impact on biodiversity.'),
    ('hard', 'english', 'She conducted an in-depth investigation into the causes of the economic recession.'),
    ('hard', 'english', 'The doctor explained the intricacies of the surgery, emphasizing its risks and potential benefits.'),
    ('hard', 'english', 'They were forced to confront hard truths about their own behavior during the therapy sessions.'),
    ('hard', 'english', 'The sudden change in policy left many businesses struggling to adapt to the new regulations.'),
    ('hard', 'english', 'He was known for his unconventional approach to leadership, prioritizing creativity over conformity.');""")

    cur.execute("""INSERT INTO sentences (difficulty, language, sentence) VALUES
    ('easy', 'spanish', 'Necesito comprar pan.'),
    ('easy', 'spanish', 'El clima está soleado hoy.'),
    ('easy', 'spanish', 'A ella le encanta leer libros por la tarde.'),
    ('easy', 'spanish', '¿Puedes ayudarme con mi tarea?'),
    ('easy', 'spanish', 'Fui al mercado a comprar verduras.'),
    ('easy', 'spanish', 'Él está jugando al fútbol con sus amigos.'),
    ('easy', 'spanish', 'El gato está durmiendo en el sofá.'),
    ('easy', 'spanish', 'Me gusta tomar café por la mañana.'),
    ('easy', 'spanish', 'Ellos están viendo una película ahora mismo.'),
    ('easy', 'spanish', 'El perro ladró fuerte en el jardín.'),
    ('easy', 'spanish', 'Ella está leyendo un libro en el sillón.'),
    ('easy', 'spanish', 'Tengo un teléfono nuevo.'),
    ('easy', 'spanish', 'Mi amigo viene mañana.'),
    ('easy', 'spanish', 'Me gusta comer pizza los fines de semana.'),
    ('easy', 'spanish', 'Los niños están jugando afuera.'),
    ('easy', 'spanish', 'Necesito comprar leche.'),
    ('easy', 'spanish', 'Vamos al parque más tarde.'),
    ('easy', 'spanish', 'A ella le gusta escuchar música en el coche.'),
    ('easy', 'spanish', 'El profesor está explicando la lección.'),
    ('easy', 'spanish', 'Estoy muy cansado hoy.'),
    ('easy', 'spanish', 'Él es mi mejor amigo.'),
    ('easy', 'spanish', 'Ella lleva un vestido rojo.'),
    ('easy', 'spanish', 'Me encanta ver películas los viernes por la noche.'),
    ('easy', 'spanish', 'Me gusta leer libros antes de dormir.'),
    ('easy', 'spanish', 'Almorzamos en el restaurante nuevo.'),
    ('easy', 'spanish', 'Mi hermano es muy alto.'),
    ('easy', 'spanish', 'El bebé está llorando en la cuna.'),
    ('easy', 'spanish', 'Disfruto caminar en el parque.'),
    ('easy', 'spanish', 'Voy a la tienda a comprar víveres.'),
    ('easy', 'spanish', 'Él está preparando el desayuno ahora.'),
    ('easy', 'spanish', 'Ella va al gimnasio esta tarde.'),
    ('easy', 'spanish', 'Voy a visitar a mi abuela mañana.'),
    ('easy', 'spanish', 'Haremos una barbacoa este fin de semana.'),
    ('easy', 'spanish', 'Necesito encontrar mis llaves.'),
    ('easy', 'spanish', 'Ella está tomando una siesta ahora.'),
    ('easy', 'spanish', 'Me encanta viajar a nuevos lugares.'),
    ('easy', 'spanish', 'Mis padres están fuera de la ciudad esta semana.'),
    ('easy', 'spanish', 'Él siempre está dispuesto a ayudar a los demás.'),
    ('easy', 'spanish', 'Nos vamos de vacaciones el mes que viene.'),
    ('easy', 'spanish', 'Mi color favorito es el azul.'),
    ('easy', 'spanish', 'Me gusta comer helado en verano.'),
    ('easy', 'spanish', 'Fui a correr esta mañana.'),
    ('easy', 'spanish', 'Ellos están jugando videojuegos juntos.'),
    ('easy', 'spanish', 'Necesito limpiar mi cuarto.'),
    ('easy', 'spanish', 'El bebé está aprendiendo a caminar.'),
    ('easy', 'spanish', 'Vi un pájaro volando en el cielo.'),
    ('easy', 'spanish', 'Estoy estudiando para mis exámenes.'),
    ('easy', 'spanish', 'Él es muy bueno en matemáticas.'),
    ('easy', 'spanish', 'Vamos a un concierto esta noche.');""")

    cur.execute("""INSERT INTO sentences (difficulty, language, sentence) VALUES
    ('intermediate', 'spanish', 'Ella está planeando mudarse a otra ciudad el próximo año.'),
    ('intermediate', 'spanish', 'He estado trabajando en este proyecto durante un mes.'),
    ('intermediate', 'spanish', 'Tomó el libro de la estantería y comenzó a leerlo.'),
    ('intermediate', 'spanish', 'Necesitamos terminar esta tarea antes de que termine el día.'),
    ('intermediate', 'spanish', 'Ella siempre lleva un paraguas cuando parece que va a llover.'),
    ('intermediate', 'spanish', 'No pude encontrar mis llaves esta mañana, así que llegué tarde.'),
    ('intermediate', 'spanish', 'Ellos están preparando la conferencia para la próxima semana.'),
    ('intermediate', 'spanish', 'El equipo está practicando para el gran partido de mañana.'),
    ('intermediate', 'spanish', 'Ella compró un vestido nuevo para la fiesta de este fin de semana.'),
    ('intermediate', 'spanish', 'A él le gusta cocinar para su familia los domingos.'),
    ('intermediate', 'spanish', 'He escuchado que el nuevo restaurante es realmente bueno.'),
    ('intermediate', 'spanish', 'Los estudiantes están trabajando en sus proyectos finales.'),
    ('intermediate', 'spanish', 'Ellos fueron a la playa a disfrutar del atardecer anoche.'),
    ('intermediate', 'spanish', 'Acabo de terminar de leer un libro sobre historia.'),
    ('intermediate', 'spanish', 'Vamos a explorar la ciudad mañana.'),
    ('intermediate', 'spanish', 'Ella pidió direcciones para llegar a la biblioteca más cercana.'),
    ('intermediate', 'spanish', 'Estoy planeando comenzar un nuevo hobby el próximo mes.'),
    ('intermediate', 'spanish', 'Estaban discutiendo sus planes para el fin de semana.'),
    ('intermediate', 'spanish', 'Él está estudiando francés porque planea viajar a París.'),
    ('intermediate', 'spanish', 'He estado sintiéndome un poco mal últimamente.'),
    ('intermediate', 'spanish', 'Los niños estaban emocionados por el viaje escolar.'),
    ('intermediate', 'spanish', 'Voy a probar una receta nueva para la cena esta noche.'),
    ('intermediate', 'spanish', 'Ella estaba leyendo una novela sobre aventura y misterio.'),
    ('intermediate', 'spanish', 'Necesitamos limpiar la casa antes de que lleguen los invitados.'),
    ('intermediate', 'spanish', 'El profesor nos dio una tarea interesante para la semana.'),
    ('intermediate', 'spanish', 'Pasé la tarde en la biblioteca preparando mis exámenes.'),
    ('intermediate', 'spanish', 'Él pasó la tarde en una reunión con sus colegas.'),
    ('intermediate', 'spanish', 'Necesito comprar una nueva laptop porque la mía está vieja.'),
    ('intermediate', 'spanish', 'Decidieron tomarse unas vacaciones en las montañas este verano.'),
    ('intermediate', 'spanish', 'Ella está aprendiendo a tocar la guitarra en su tiempo libre.'),
    ('intermediate', 'spanish', 'Vamos al museo a ver la nueva exposición.'),
    ('intermediate', 'spanish', 'He estado trabajando en mejorar mi nivel de forma física.'),
    ('intermediate', 'spanish', 'Él decidió cambiar de carrera y mudarse a otra industria.'),
    ('intermediate', 'spanish', 'Me encanta pasar tiempo con mis amigos los fines de semana.'),
    ('intermediate', 'spanish', 'El concierto estuvo increíble y nos divertimos mucho.'),
    ('intermediate', 'spanish', 'Ella es muy creativa y le encanta pintar en su tiempo libre.'),
    ('intermediate', 'spanish', 'Estoy esperando con ansias las vacaciones de este año.'),
    ('intermediate', 'spanish', 'Ellos se quedaron despiertos hasta tarde viendo una película nueva en Netflix.'),
    ('intermediate', 'spanish', 'Él suele salir a correr por la mañana antes del trabajo.'),
    ('intermediate', 'spanish', 'Vamos a organizar una cena en nuestra casa este fin de semana.'),
    ('intermediate', 'spanish', 'El proyecto vence en dos semanas, así que necesitamos trabajar duro.'),
    ('intermediate', 'spanish', 'Ella está planeando estudiar en el extranjero para su posgrado.'),
    ('intermediate', 'spanish', 'Estoy emocionado por el nuevo libro que acabo de empezar a leer.'),
    ('intermediate', 'spanish', 'Pasamos la tarde caminando por el centro de la ciudad.'),
    ('intermediate', 'spanish', 'La empresa lanzará un nuevo producto el mes que viene.'),
    ('intermediate', 'spanish', 'Estuvieron discutiendo sus planes para la temporada de vacaciones.'),
    ('intermediate', 'spanish', 'Ella está participando en una competencia de cocina este fin de semana.'),
    ('intermediate', 'spanish', 'Necesito comprar ropa nueva para la temporada de invierno.');""")

    cur.execute("""INSERT INTO sentences (difficulty, language, sentence) VALUES
    ('hard', 'spanish', 'A pesar de la lluvia intensa, decidieron continuar su viaje sin dudar.'),
    ('hard', 'spanish', 'El político dio un discurso poderoso sobre el futuro de la economía y la educación.'),
    ('hard', 'spanish', 'Se encontraba atrapado en un dilema moral, sin saber qué decisión era la correcta.'),
    ('hard', 'spanish', 'El científico presentó una teoría innovadora que desafió las creencias existentes.'),
    ('hard', 'spanish', 'La película abordó temas profundos sobre la moralidad, la justicia y el sacrificio.'),
    ('hard', 'spanish', 'El autor logró captar la complejidad emocional de sus personajes de manera impresionante.'),
    ('hard', 'spanish', 'La decisión de la empresa de reducir personal generó un gran debate en la comunidad.'),
    ('hard', 'spanish', 'Su investigación sobre el cambio climático fue reconocida a nivel internacional.'),
    ('hard', 'spanish', 'El escritor retrató las dificultades de la vida humana con un estilo único y cautivador.'),
    ('hard', 'spanish', 'A pesar de sus esfuerzos, no pudo resolver el conflicto interno que lo aquejaba.'),
    ('hard', 'spanish', 'La presentación del proyecto fue tan detallada que dejó a todos los presentes asombrados.'),
    ('hard', 'spanish', 'El filósofo exploró la naturaleza de la existencia humana a través de un análisis profundo.'),
    ('hard', 'spanish', 'El músico dedicó años a perfeccionar su habilidad, alcanzando un nivel de destreza excepcional.'),
    ('hard', 'spanish', 'El gobierno implementó una nueva política económica destinada a mejorar la competitividad internacional.'),
    ('hard', 'spanish', 'El arquitecto presentó una propuesta innovadora para la renovación del centro histórico.'),
    ('hard', 'spanish', 'El conflicto en la región se intensificó a medida que las tensiones políticas aumentaron.'),
    ('hard', 'spanish', 'Los efectos del cambio climático ya son visibles en muchas partes del mundo.'),
    ('hard', 'spanish', 'El debate sobre el uso de la inteligencia artificial en la medicina es cada vez más relevante.'),
    ('hard', 'spanish', 'La teoría del caos propone que incluso los sistemas complejos pueden ser impredecibles.'),
    ('hard', 'spanish', 'El equipo de investigación descubrió un vínculo entre las enfermedades cardiovasculares y el estrés crónico.'),
    ('hard', 'spanish', 'El artista fue elogiado por su capacidad de transformar la tragedia en belleza a través de su obra.'),
    ('hard', 'spanish', 'La novela exploró la lucha interna del protagonista entre el deber y el deseo personal.'),
    ('hard', 'spanish', 'Los avances tecnológicos están cambiando rápidamente la forma en que vivimos y trabajamos.'),
    ('hard', 'spanish', 'La decisión de invertir en energías renovables podría transformar el futuro de la industria energética.'),
    ('hard', 'spanish', 'El escritor no temió abordar temas polémicos, incluso cuando su trabajo fue objeto de controversia.'),
    ('hard', 'spanish', 'Las reformas educativas propuestas tienen el potencial de cambiar la forma en que se enseña en todo el país.'),
    ('hard', 'spanish', 'El nuevo tratado internacional busca establecer normas más estrictas para la protección del medio ambiente.'),
    ('hard', 'spanish', 'La historia de su vida fue un testimonio de la resiliencia humana frente a la adversidad.'),
    ('hard', 'spanish', 'La sociedad moderna enfrenta desafíos éticos complejos debido al progreso tecnológico y científico.'),
    ('hard', 'spanish', 'A pesar de sus dudas, decidió emprender el viaje, sabiendo que era una oportunidad única en la vida.'),
    ('hard', 'spanish', 'El filósofo defendió la idea de que la moralidad debe basarse en principios universales, no en normas sociales.'),
    ('hard', 'spanish', 'La investigación sobre las causas del cambio climático continúa siendo una prioridad mundial.'),
    ('hard', 'spanish', 'La conferencia abordó los desafíos éticos que presenta la inteligencia artificial en el ámbito laboral.'),
    ('hard', 'spanish', 'La escritora utilizó su plataforma para abogar por los derechos de las mujeres en el mundo laboral.'),
    ('hard', 'spanish', 'El descubrimiento de una nueva especie de dinosaurio revolucionó el campo de la paleontología.'),
    ('hard', 'spanish', 'El experto en neurociencia presentó sus hallazgos sobre la relación entre el cerebro y las emociones.'),
    ('hard', 'spanish', 'La ciudad ha experimentado un rápido crecimiento en los últimos años debido a la inmigración y la industrialización.');""")

    con.commit()
    
con.close()

print("Base de datos para el juego creada")

